# Generated by Django 4.0.3 on 2022-08-17 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeFixed',
            fields=[
                ('ip', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('host_name', models.CharField(max_length=50)),
                ('total_gpu_memory_capacity_mb', models.IntegerField(db_column='total_gpu_memory_capacity_MB')),
                ('number_of_gpu', models.IntegerField()),
                ('total_disk_capacity_gb', models.IntegerField(db_column='total_disk_capacity_GB')),
                ('total_memory_capacity_gb', models.IntegerField(db_column='total_memory_capacity_GB')),
                ('number_of_core', models.IntegerField()),
                ('number_of_thread', models.IntegerField()),
                ('cpu_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NodeChanged',
            fields=[
                ('node_changed_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_gpu_memory_using_percent', models.FloatField()),
                ('total_gpu_memory_using_mb', models.FloatField(db_column='total_gpu_memory_using_MB')),
                ('free_disk_gb', models.IntegerField(db_column='free_disk_GB')),
                ('free_memory_gb', models.IntegerField(db_column='free_memory_GB')),
                ('free_disk_percent', models.FloatField()),
                ('total_memory_using_percent', models.FloatField()),
                ('total_cpu_using_percent', models.FloatField()),
                ('free_cpu_percent', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.ForeignKey(db_column='ip', on_delete=django.db.models.deletion.CASCADE, to='base.nodefixed')),
            ],
        ),
        migrations.CreateModel(
            name='GpuFixed',
            fields=[
                ('gpu_fixed_id', models.AutoField(primary_key=True, serialize=False)),
                ('gpu_name', models.CharField(max_length=50)),
                ('gpu_index', models.IntegerField()),
                ('each_total_gpu_memory_capacity_mb', models.IntegerField(db_column='each_total_gpu_memory_capacity_MB')),
                ('ip', models.ForeignKey(db_column='ip', on_delete=django.db.models.deletion.CASCADE, to='base.nodefixed')),
            ],
        ),
        migrations.CreateModel(
            name='GpuChanged',
            fields=[
                ('gpu_changed_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gpu_memory_using_mb', models.IntegerField(db_column='gpu_memory_using_MB')),
                ('gpu_memory_using_percent', models.FloatField()),
                ('gpu_index', models.IntegerField()),
                ('ip', models.ForeignKey(db_column='ip', on_delete=django.db.models.deletion.CASCADE, to='base.nodefixed')),
            ],
        ),
        migrations.CreateModel(
            name='DiskFixed',
            fields=[
                ('disk_fixed_id', models.AutoField(primary_key=True, serialize=False)),
                ('disk_path', models.CharField(max_length=50)),
                ('each_total_disk_capacity_gb', models.IntegerField(db_column='each_total_disk_capacity_GB')),
                ('ip', models.ForeignKey(db_column='ip', on_delete=django.db.models.deletion.CASCADE, to='base.nodefixed')),
            ],
        ),
        migrations.CreateModel(
            name='DiskChanged',
            fields=[
                ('disk_changed_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('disk_using_gb', models.IntegerField(db_column='disk_using_GB')),
                ('disk_using_percent', models.FloatField()),
                ('disk_path', models.CharField(max_length=50)),
                ('ip', models.ForeignKey(db_column='ip', on_delete=django.db.models.deletion.CASCADE, to='base.nodefixed')),
            ],
        ),
    ]
