# Generated by Django 4.0.3 on 2022-08-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodefixed',
            name='ip',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
