# Generated by Django 4.0.3 on 2022-08-17 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_nodefixed_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodefixed',
            old_name='total_disk_capacity_gb',
            new_name='total_disk_capacity_GB',
        ),
        migrations.RenameField(
            model_name='nodefixed',
            old_name='total_gpu_memory_capacity_mb',
            new_name='total_gpu_memory_capacity_MB',
        ),
        migrations.RenameField(
            model_name='nodefixed',
            old_name='total_memory_capacity_gb',
            new_name='total_memory_capacity_GB',
        ),
    ]
