# Generated by Django 4.0.3 on 2022-08-17 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_total_disk_capacity_gb_nodefixed_total_disk_capacity_gb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diskfixed',
            old_name='each_total_disk_capacity_gb',
            new_name='each_total_disk_capacity_GB',
        ),
    ]
