# Generated by Django 4.0.3 on 2022-08-17 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_each_total_disk_capacity_gb_diskfixed_each_total_disk_capacity_gb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpufixed',
            old_name='each_total_gpu_memory_capacity_mb',
            new_name='each_total_gpu_memory_capacity_MB',
        ),
    ]
