# Generated by Django 4.0.3 on 2022-08-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_each_total_gpu_memory_capacity_mb_gpufixed_each_total_gpu_memory_capacity_mb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diskchanged',
            old_name='disk_using_gb',
            new_name='disk_using_GB',
        ),
        migrations.RenameField(
            model_name='gpuchanged',
            old_name='gpu_memory_using_mb',
            new_name='gpu_memory_using_MB',
        ),
        migrations.RenameField(
            model_name='nodechanged',
            old_name='free_disk_gb',
            new_name='free_disk_GB',
        ),
        migrations.RenameField(
            model_name='nodechanged',
            old_name='free_memory_gb',
            new_name='free_memory_GB',
        ),
        migrations.RenameField(
            model_name='nodechanged',
            old_name='total_gpu_memory_using_mb',
            new_name='total_gpu_memory_using_MB',
        ),
    ]
