# Generated by Django 4.0.3 on 2022-08-12 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NODE_FIXED',
            fields=[
                ('ip', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('host_name', models.CharField(max_length=50)),
                ('total_gpu_memory_capacity_MB', models.IntegerField()),
                ('number_of_gpu', models.IntegerField()),
                ('total_disk_capacity_GB', models.IntegerField()),
                ('total_memory_capacity_GB', models.IntegerField()),
                ('cpu_name', models.CharField(max_length=50)),
                ('number_of_core', models.IntegerField()),
                ('number_of_thread', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NODE_CHANGE',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('total_gpu_memory_using_percent', models.FloatField()),
                ('total_gpu_memory_using_MB', models.FloatField()),
                ('free_disk_GB', models.IntegerField()),
                ('free_memory_GB', models.IntegerField()),
                ('free_disk_percent', models.FloatField()),
                ('total_memory_using_percent', models.FloatField()),
                ('total_cpu_using_percent', models.FloatField()),
                ('free_cpu_percent', models.FloatField()),
                ('ip', models.ForeignKey(db_column='ip', on_delete=django.db.models.deletion.CASCADE, to='tonyApp.node_fixed')),
            ],
        ),
        migrations.CreateModel(
            name='GPU_FIXED',
            fields=[
                ('gpu_index', models.IntegerField(primary_key=True, serialize=False)),
                ('each_total_gpu_memory_capacity_MB', models.IntegerField()),
                ('gpu_name', models.CharField(max_length=20)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tonyApp.node_fixed')),
            ],
        ),
        migrations.CreateModel(
            name='GPU_CHANGE',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('gpu_memory_using_MB', models.IntegerField()),
                ('gpu_memory_using_percent', models.FloatField()),
                ('gpu_index', models.ForeignKey(db_column='gpu_index', on_delete=django.db.models.deletion.CASCADE, to='tonyApp.gpu_fixed')),
                ('ip', models.ForeignKey(db_column='ip', on_delete=django.db.models.deletion.CASCADE, to='tonyApp.node_fixed')),
            ],
        ),
        migrations.CreateModel(
            name='DISK_FIXED',
            fields=[
                ('disk_path', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('each_total_disk_capacity_GB', models.IntegerField()),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tonyApp.node_fixed')),
            ],
        ),
        migrations.CreateModel(
            name='DISK_CHANGE',
            fields=[
                ('create_at', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('disk_using_GB', models.IntegerField()),
                ('disk_using_percent', models.IntegerField()),
                ('disk_path', models.ForeignKey(db_column='disk_path', on_delete=django.db.models.deletion.CASCADE, to='tonyApp.disk_fixed')),
                ('ip', models.ForeignKey(db_column='ip', on_delete=django.db.models.deletion.CASCADE, to='tonyApp.node_fixed')),
            ],
        ),
        migrations.AddConstraint(
            model_name='node_change',
            constraint=models.UniqueConstraint(fields=('create_at', 'ip'), name='NODE_CHANGE_MIX'),
        ),
        migrations.AddConstraint(
            model_name='gpu_fixed',
            constraint=models.UniqueConstraint(fields=('gpu_index', 'ip'), name='GPU_FIXED_MIX'),
        ),
        migrations.AddConstraint(
            model_name='gpu_change',
            constraint=models.UniqueConstraint(fields=('create_at', 'gpu_index', 'ip'), name='GPU_CHANGE_MIX'),
        ),
        migrations.AddConstraint(
            model_name='disk_fixed',
            constraint=models.UniqueConstraint(fields=('disk_path', 'ip'), name='DISK_FIXED_MIX'),
        ),
        migrations.AddConstraint(
            model_name='disk_change',
            constraint=models.UniqueConstraint(fields=('create_at', 'disk_path', 'ip'), name='DISK_CHANGE_MIX'),
        ),
    ]
