# Generated by Django 4.0.3 on 2022-08-12 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tonyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpu_change',
            old_name='created_at',
            new_name='create_at',
        ),
    ]
