# Generated by Django 4.0.3 on 2022-08-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tonyApp', '0002_rename_created_at_gpu_change_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskChange',
            fields=[
                ('create_at', models.DateTimeField(primary_key=True, serialize=False)),
                ('disk_using_gb', models.IntegerField(db_column='disk_using_GB')),
                ('disk_using_percent', models.FloatField()),
            ],
            options={
                'db_table': 'DISK_CHANGE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiskFixed',
            fields=[
                ('disk_path', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('each_total_disk_capacity_gb', models.IntegerField(db_column='each_total_disk_capacity_GB')),
            ],
            options={
                'db_table': 'DISK_FIXED',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GpuChange',
            fields=[
                ('created_at', models.DateTimeField(primary_key=True, serialize=False)),
                ('gpu_memory_using_mb', models.IntegerField(db_column='gpu_memory_using_MB')),
                ('gpu_memory_using_percent', models.FloatField()),
            ],
            options={
                'db_table': 'GPU_CHANGE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GpuFixed',
            fields=[
                ('gpu_index', models.IntegerField(primary_key=True, serialize=False)),
                ('each_total_gpu_memory_capacity_mb', models.IntegerField(db_column='each_total_gpu_memory_capacity_MB')),
                ('gpu_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'GPU_FIXED',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NodeChange',
            fields=[
                ('created_at', models.DateTimeField(primary_key=True, serialize=False)),
                ('total_gpu_memory_using_percent', models.FloatField()),
                ('total_gpu_memory_using_mb', models.FloatField(db_column='total_gpu_memory_using_MB')),
                ('free_disk_gb', models.IntegerField(db_column='free_disk_GB')),
                ('free_memory_gb', models.IntegerField(db_column='free_memory_GB')),
                ('free_disk_percent', models.FloatField()),
                ('total_memory_using_percent', models.FloatField()),
                ('total_cpu_using_percent', models.FloatField()),
                ('free_cpu_percent', models.FloatField()),
            ],
            options={
                'db_table': 'NODE_CHANGE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NodeFixed',
            fields=[
                ('ip', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('host_name', models.CharField(max_length=50)),
                ('total_gpu_memory_capacity_mb', models.IntegerField(db_column='total_gpu_memory_capacity_MB')),
                ('number_of_gpu', models.IntegerField()),
                ('total_disk_capacity_gb', models.IntegerField(db_column='total_disk_capacity_GB')),
                ('total_memory_capacity_gb', models.IntegerField(db_column='total_memory_capacity_GB')),
                ('number_of_core', models.IntegerField()),
                ('number_of_thread', models.IntegerField()),
                ('cpu_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'NODE_FIXED',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='disk_fixed',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='gpu_change',
            name='gpu_index',
        ),
        migrations.RemoveField(
            model_name='gpu_change',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='gpu_fixed',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='node_change',
            name='ip',
        ),
        migrations.DeleteModel(
            name='DISK_CHANGE',
        ),
        migrations.DeleteModel(
            name='DISK_FIXED',
        ),
        migrations.DeleteModel(
            name='GPU_CHANGE',
        ),
        migrations.DeleteModel(
            name='GPU_FIXED',
        ),
        migrations.DeleteModel(
            name='NODE_CHANGE',
        ),
        migrations.DeleteModel(
            name='NODE_FIXED',
        ),
    ]
