# Generated by Django 4.0.3 on 2022-08-12 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeFixed',
            fields=[
                ('ip', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('host_name', models.CharField(max_length=50)),
                ('total_gpu_memory_capacity_MB', models.IntegerField()),
                ('number_of_gpu', models.IntegerField()),
                ('total_disk_capacity_GB', models.IntegerField()),
                ('total_memory_capacity_GB', models.IntegerField()),
                ('cpu_name', models.CharField(max_length=50)),
                ('number_of_core', models.IntegerField()),
                ('number_of_thread', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NodeChanged',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('total_gpu_memory_using_percent', models.FloatField()),
                ('total_gpu_memory_using_MB', models.FloatField()),
                ('free_disk_GB', models.IntegerField()),
                ('free_memory_GB', models.IntegerField()),
                ('free_disk_percent', models.FloatField()),
                ('total_memory_using_percent', models.FloatField()),
                ('total_cpu_using_percent', models.FloatField()),
                ('free_cpu_percent', models.FloatField()),
                ('ip', models.ForeignKey(db_column='ip', on_delete=django.db.models.deletion.CASCADE, to='baro.nodefixed')),
            ],
        ),
        migrations.CreateModel(
            name='GPUFixed',
            fields=[
                ('gpu_index', models.IntegerField(primary_key=True, serialize=False)),
                ('each_total_gpu_memory_capacity_MB', models.IntegerField()),
                ('gpu_name', models.CharField(max_length=50)),
                ('ip', models.ForeignKey(db_column='ip', on_delete=django.db.models.deletion.CASCADE, to='baro.nodefixed')),
            ],
        ),
        migrations.CreateModel(
            name='GPUChanged',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('gpu_memory_using_MB', models.IntegerField()),
                ('gpu_memory_using_percent', models.FloatField()),
                ('gpu_index', models.ForeignKey(db_column='gpu_index', on_delete=django.db.models.deletion.CASCADE, to='baro.gpufixed')),
                ('ip', models.ForeignKey(db_column='ip', on_delete=django.db.models.deletion.CASCADE, to='baro.nodefixed')),
            ],
        ),
        migrations.CreateModel(
            name='DiskFixed',
            fields=[
                ('disk_path', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('each_total_disk_capacity_GB', models.IntegerField()),
                ('ip', models.ForeignKey(db_column='ip', on_delete=django.db.models.deletion.CASCADE, to='baro.nodefixed')),
            ],
        ),
        migrations.CreateModel(
            name='DiskChanged',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('disk_using_GB', models.IntegerField()),
                ('disk_using_percent', models.IntegerField()),
                ('disk_path', models.ForeignKey(db_column='disk_path', on_delete=django.db.models.deletion.CASCADE, to='baro.diskfixed')),
                ('ip', models.ForeignKey(db_column='ip', on_delete=django.db.models.deletion.CASCADE, to='baro.nodefixed')),
            ],
        ),
        migrations.AddConstraint(
            model_name='nodechanged',
            constraint=models.UniqueConstraint(fields=('created_at', 'ip'), name='created_at_ip'),
        ),
        migrations.AddConstraint(
            model_name='gpufixed',
            constraint=models.UniqueConstraint(fields=('gpu_index', 'ip'), name='gpu_index_ip'),
        ),
        migrations.AddConstraint(
            model_name='gpuchanged',
            constraint=models.UniqueConstraint(fields=('gpu_index', 'ip', 'created_at'), name='gpu_index_ip_created_at'),
        ),
        migrations.AddConstraint(
            model_name='diskfixed',
            constraint=models.UniqueConstraint(fields=('disk_path', 'ip'), name='ip_disk_path'),
        ),
        migrations.AddConstraint(
            model_name='diskchanged',
            constraint=models.UniqueConstraint(fields=('disk_path', 'ip', 'created_at'), name='ip_disk_path_created_at'),
        ),
    ]
